language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: pep4ak
  password:
    secure: TPsquN4BJcRntBok0sc77htgG5CluKMKM0eQZWdRrffLuEvsFXpQDIDPkaU+nzPEHUhnAhD9AtLkN0HlCja+3r2iJ7iUwvG5Yab9NHpXOlwUkha5EU9CeBsyATgNqNZtvf7sB7cnmKFgX0DVPfVy3xQpg4/X/u3xhtOR+YYOVG1Ti7vTBQ8rHtzla/7MTvs54asehCG1t6K7VetGqonYCpdvkc5HkDxvZx14J3azZXgzu/oLd6N1jT1GSW2wm8nkkgLs7zeuUYhb2GwVbZr+3FqHXo0oCJAJc03GxW+IBhg+CO0PFzb2UsK1C0Vo6dZlKVlCAcT8bbH7iWvvaiCBzMoIvJp0J6aA7LJHrJxUpDDBbqh4dRa4VbH9kflfOkakKUOliQ6iP0Lx0ts7VsVwewteDooWhG8t7pUsBq6ceUD7eIiEYF3UYpdt3mh3UUI/J94HTxALhptX+ttUf6y8qRzRsmwKYHGBP1VmMlVrAA81snkcYb6TWTvdtQIv38ESv0cVZQdNpXy4giCWnMopgu0o9nQcaWP5Te/LIJt47i367W9x5O8QKAWfjIzXlm4rY+5vz3dP2KPfANlEu0onrP/IgWzxAF0euHTlVqgVksuSHINACeXQm9eMyEaBApzgnsorJBDqzdZtVBJG9xSKA/CjBdLzIOjgnAD0DfAmMso=
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.9
after_script:
  - echo "Deploy to PyPI finished."